<a href="https://colab.research.google.com/github/thetestcoder/ml-projects/blob/main/ML_6_Handwritten_Digit_Recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir ~/.kaggle
!cp kaggle.json ~/.kaggle
!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!kaggle datasets download pradheeprio/handwritten-digit-classification

 53% 10.0M/19.0M [00:00<00:00, 30.5MB/s]
100% 19.0M/19.0M [00:00<00:00, 49.2MB/s]


In [5]:
!unzip handwritten-digit-classification.zip

Streaming output truncated to the last 5000 lines.
  inflating: database/8/train_38_01002.png  
  inflating: database/8/train_38_01003.png  
  inflating: database/8/train_38_01004.png  
  inflating: database/8/train_38_01005.png  
  inflating: database/8/train_38_01006.png  
  inflating: database/8/train_38_01007.png  
  inflating: database/8/train_38_01008.png  
  inflating: database/8/train_38_01009.png  
  inflating: database/8/train_38_01010.png  
  inflating: database/8/train_38_01011.png  
  inflating: database/8/train_38_01012.png  
  inflating: database/8/train_38_01013.png  
  inflating: database/8/train_38_01014.png  
  inflating: database/8/train_38_01015.png  
  inflating: database/8/train_38_01016.png  
  inflating: database/8/train_38_01017.png  
  inflating: database/8/train_38_01018.png  
  inflating: database/8/train_38_01019.png  
  inflating: database/8/train_38_01020.png  
  inflating: database/8/train_38_01021.png  
  inflating: database/8/train_38_01022.png  
  in

In [6]:
!pip install pillow

In [11]:
#preprocessing data
import os
import numpy as np
from PIL import Image

data_directory  = 'database/'

preprocessed_images = []
labels = []

for label in os.listdir(data_directory):
  label_dir = os.path.join(data_directory, label)
  if os.path.isdir(label_dir):
    for filename in os.listdir(label_dir):
      if filename.endswith('.png'):
        img = Image.open(os.path.join(label_dir, filename))
        img = img.resize((28, 28))
        img = img.convert("L")
        img_array = np.array(img)
        img_array = img_array / 255.0
        img_flattened = img_array.flatten()

        preprocessed_images.append(img_flattened)
        labels.append(int(label))


X = np.array(preprocessed_images)
y = np.array(labels)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

svm_clf = SVC()

svm_clf.fit(X_train, y_train)

SVC()

In [13]:
y_pred = svm_clf.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Calculate precision
precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", precision)

# Calculate recall
recall = recall_score(y_test, y_pred, average='weighted')
print("Recall:", recall)

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.9768410529823393
Precision: 0.9768517204074992
Recall: 0.9768410529823393
Confusion Matrix:
 [[615   1   2   2   0   1   0   0   2   1]
 [  0 621   0   1   0   0   0   1   0   0]
 [  2   0 579   2   1   1   1   0   5   2]
 [  3   3   1 563   0   3   0   2   2   0]
 [  0   0   2   0 576   0   3   1   2  10]
 [  1   5   2   8   0 593   0   1   1   1]
 [  0   0   0   0   0   4 617   0   1   0]
 [  0   3   0   0   2   0   0 568   2   5]
 [  0   2   2   5   4   2   1   1 590   3]
 [  1   1   0   0  12   2   0  10   0 541]]
